services:
    dm_admin.twig.delete_form_extension:
        class: Dm\Bundle\AdminBundle\Twig\DeleteFormExtension
        arguments: [ @twig ]   
        tags:                  
            - { name: twig.extension } 
    dm_admin.twig.logout_path_extension:
        class: Dm\Bundle\AdminBundle\Twig\LogoutPathExtension
        arguments: [ @security.logout_url_generator ]   
        tags:                  
            - { name: twig.extension } 
    dm_admin.extension.icon:
        class: Dm\Bundle\AdminBundle\Extension\IconExtension
        public: false
        tags:
            - { name: knp_menu.factory_extension }

    dm_admin.doctrine_upload_listener:
        class: Dm\Bundle\AdminBundle\EventListener\UploadListener
        arguments: 
            - '%kernel.root_dir%/../web'
            - @filesystem
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }
